{{- range .Values.versions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ $.Release.Name }}
    version: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      version: {{ .name }}
  template:
    metadata:
      name: {{ $.Release.Name }}-{{ .name }}
      labels:
        app: {{ $.Release.Name }}
        version: {{ .name }}
    spec:
      containers:
       - image: bitloops/{{ $.Release.Name }}:{{ .image.tag }}
         name: {{ $.Release.Name }}-{{ .name }}
         env:
         {{- range $key, $value := $.Values.env }}
         - name: {{ $key }}
           value: "{{ $value }}"
         {{- end }}
         - name: VERSION
           value: {{ .name }}
         - name: "NATS_USER"
           valueFrom:
             secretKeyRef:
               key:  nats_user
               name: {{ $.Release.Name }}-secret
         - name: "NATS_PASSWORD"
           valueFrom:
             secretKeyRef:
               key:  nats_password
               name: {{ $.Release.Name }}-secret
         - name: "REDIS_USERNAME"
           valueFrom:
             secretKeyRef:
               key:  redis_username
               name: {{ $.Release.Name }}-secret
         - name: "REDIS_PASSWORD"
           valueFrom:
             secretKeyRef:
               key:  redis_password
               name: {{ $.Release.Name }}-secret
         - name: "ENCRYPTION_KEY"
           valueFrom:
             secretKeyRef:
               key:  encryption_key
               name: {{ $.Release.Name }}-secret
         - name: "MONGO_USER"
           valueFrom:
             secretKeyRef:
               key: mongo_user
               name: {{ $.Release.Name }}-secret
         - name: "MONGO_PASSWORD"
           valueFrom:
             secretKeyRef:
               key: mongo_password
               name: {{ $.Release.Name }}-secret
         - name: "ADMIN_WORKSPACE_ID"
           valueFrom:
             secretKeyRef:
               key: admin_workspace_id
               name: {{ $.Release.Name }}-secret
         ports:
          - containerPort: 8080
            protocol: TCP
         resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 250m
         livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
         readinessProbe: 
            httpGet:
                path: /ready
                port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20 
      imagePullSecrets:
      - name: regcred
---
{{- end }}